CREATE TABLE "clientes" (
  "cliente_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cliente_nacionalidad" char NOT NULL,
  "cliente_cedula" integer NOT NULL,
  "cliente_nombre" text NOT NULL,
  "cliente_apellido" text NOT NULL,
  "cliente_telefono" text,
  "cliente_direccion" text
);

CREATE TABLE "detalles_ordenes_divisas" (
  "detalle_orden_divisa_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "orden_id" integer NOT NULL,
  "divisa_id" integer NOT NULL,
  "detalle_orden_divisa_cantidad" double precision NOT NULL
);

CREATE TABLE "detalles_ordenes_platos" (
  "detalle_orden_plato_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "orden_id" integer NOT NULL,
  "plato_id" integer NOT NULL,
  "detalle_orden_plato_cantidad" integer NOT NULL
);

CREATE TABLE "divisas" (
  "divisa_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "divisa_nombre" text NOT NULL,
  "divisa_relacion" double precision NOT NULL
);

CREATE TABLE "mesas" (
  "mesa_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "mesa_descripcion" text NOT NULL
);

CREATE TABLE "mesas_ocupadas" (
  "mesa_id" integer UNIQUE NOT NULL,
  "orden_id" integer UNIQUE NOT NULL
);

CREATE TABLE "ordenes" (
  "orden_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "orden_fecha" date NOT NULL,
  "cliente_id" integer
);

CREATE TABLE "platos" (
  "plato_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "plato_nombre" text NOT NULL,
  "plato_descripcion" text NOT NULL,
  "plato_precio" double precision NOT NULL,
  "tipo_plato_id" integer NOT NULL
);

CREATE TABLE "tipos_platos" (
  "tipo_plato_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "tipo_plato_nombre" text NOT NULL,
  "tipo_plato_icon" text
);

CREATE TABLE "usuarios" (
  "usuario_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "usuario_nombre" text NOT NULL,
  "usuario_contraseña" text NOT NULL,
  "usuario_salt" text NOT NULL,
  "rol_id" integer NOT NULL
);

CREATE TABLE "roles" (
  "rol_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "rol_nombre" text NOT NULL
);

ALTER TABLE "detalles_ordenes_divisas" ADD CONSTRAINT "detalles_ordenes_divisas_divisa_id_fkey" FOREIGN KEY ("divisa_id") REFERENCES "divisas" ("divisa_id");

ALTER TABLE "detalles_ordenes_divisas" ADD CONSTRAINT "detalles_ordenes_divisas_orden_id_fkey" FOREIGN KEY ("orden_id") REFERENCES "ordenes" ("orden_id");

ALTER TABLE "detalles_ordenes_platos" ADD CONSTRAINT "detalles_ordenes_platos_orden_id_fkey" FOREIGN KEY ("orden_id") REFERENCES "ordenes" ("orden_id");

ALTER TABLE "detalles_ordenes_platos" ADD CONSTRAINT "detalles_ordenes_platos_plato_id_fkey" FOREIGN KEY ("plato_id") REFERENCES "platos" ("plato_id");

ALTER TABLE "mesas_ocupadas" ADD CONSTRAINT "mesas_ocupadas_mesa_id_fkey" FOREIGN KEY ("mesa_id") REFERENCES "mesas" ("mesa_id");

ALTER TABLE "mesas_ocupadas" ADD CONSTRAINT "mesas_ocupadas_orden_id_fkey" FOREIGN KEY ("orden_id") REFERENCES "ordenes" ("orden_id");

ALTER TABLE "ordenes" ADD CONSTRAINT "ordenes_cliente_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("cliente_id");

ALTER TABLE "platos" ADD CONSTRAINT "platos_tipo_plato_id_fkey" FOREIGN KEY ("tipo_plato_id") REFERENCES "tipos_platos" ("tipo_plato_id");

ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_rol_id_fkey" FOREIGN KEY ("rol_id") REFERENCES "roles" ("rol_id");
